name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm dependencies
        run: npm install

      - name: Install markdown-table@2.0.1
        run: npm install markdown-table@2.0.1

      - name: Generate README
        run: |
          node ./generate-readme.js
        working-directory: scripts/

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
