name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # debug
      #   - name: Print OpenAPI file
      #     run: cat openapi/openapi.yaml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version you need

      - name: Install swagger2markup-cli
        run: wget https://jcenter.bintray.com/io/github/swagger2markup/swagger2markup-cli/1.3.3/swagger2markup-cli-1.3.3.jar -O swagger2markup-cli.jar

      - name: Convert OpenAPI to AsciiDoc
        run: java -jar swagger2markup-cli.jar convert -i openapi/openapi.yaml -f ASCIIDOC

      - name: Convert AsciiDoc to Markdown
        run: asciidoctor -b docbook -o README.md openapi/openapi.adoc

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
