name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version you need

      - name: Install npm dependencies
        run: npm install

      - name: Generate README
        run: |
          # Run the generate-readme.js script with the correct path
          node ./scripts/generate-readme.js
        working-directory: openapi/

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
