name: Generate README

on:
  push:
    branches:
      - main
    # paths:
    #     - 'openapi.yaml'

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Create temporary package.json
        run: |
          echo '{
            "name": "temp-package",
            "version": "1.0.0"
          }' > package.json

      - name: Install widdershins
        run: npm install -g widdershins

      - name: Generate Markdown documentation
        run: npx widdershins openapi/openapi.yaml -o README.md

      - name: Commit & Push changes
        run: |
          git config --global user.name "Dale-Kurt Murray"
          git config --global user.email "hello@dalekurtmurray.com"
          git add README.md
          git commit -m "Update README.md"
          git push origin main
