name: Generate README

on:
  push:
    branches:
      - main
    # paths:
    #     - 'openapi.yaml'

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install required npm packages
        run: npm install -g redoc-cli

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc

      - name: Generate README from OpenAPI
        run: redoc-cli bundle openapi/openapi.yaml -o generated-readme.html

      - name: Convert HTML to Markdown
        run: pandoc -s generated-readme.html -o README.md

      # - name: Debug - List contents of scripts directory
      #   run: ls -l ./scripts

      # - name: Debug - Cat the contents of generate-readme-esm.js
      #   run: cat ./scripts/generate-readme-esm.js

      # - name: Generate README (ESM)
      #   run: |
      #     node ./scripts/generate-readme.js

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
