name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # debug
      #   - name: Print OpenAPI file
      #     run: cat openapi/openapi.yaml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version you need

      - name: Install redoc-cli
        run: npm install -g redoc-cli

      - name: Generate README from OpenAPI spec
        run: redoc-cli bundle -o README.md openapi/openapi.yaml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
