name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
          registry-url: "https://registry.npmjs.org"

      - name: Set NODE_OPTIONS to enable ESM
        run: echo "NODE_OPTIONS=--experimental-modules" >> $GITHUB_ENV

      - name: Set package.json for ESM
        run: |
          echo '{
            "type": "module"
          }' > package.json

      - name: Install markdown-table
        run: npm install swagger-jsdoc markdown-table

      # - name: Debug - List contents of scripts directory
      #   run: ls -l ./scripts

      # - name: Debug - Cat the contents of generate-readme-esm.js
      #   run: cat ./scripts/generate-readme-esm.js

      - name: Generate README (ESM)
        run: |
          node ./scripts/generate-readme-esm.js
        working-directory: ./

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
