name: Generate README

on:
  push:
    branches:
      - main
    # paths:
    #     - 'openapi.yaml'

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install required npm packages
        run: npm install -g redoc-cli

      # - name: Generate README from OpenAPI
      #   run: redoc-cli bundle openapi/openapi.yaml -o generated-readme.html
      - name: Generate Structured JSON from OpenAPI
        run: |
          redoc-cli bundle openapi/openapi.yaml --output structured.json
          cat structured.json

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Transform Structured JSON to Markdown
        run: python scripts/transform_to_markdown.py

      # - name: Install html2md
      #   run: pip install html2md

      # - name: Convert HTML to Markdown
      #   run: |
      #     python -c "import html2md; html = open('generated-readme.html').read(); markdown = html2md.convert(html); open('README.md', 'w').write(markdown)"

      # - name: Remove Unwanted Content
      #   run: sed -i '/<script> const __redoc_state = {/,/path.../{//!d}' README.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
