name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # debug
      #   - name: Print OpenAPI file
      #     run: cat openapi/openapi.yaml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version you need

      - name: Install dependencies
        run: npm install js-yaml # Install js-yaml package

      - name: Generate README
        run: node ./scripts/generate-readme.js # Fix - Specify the correct path to the script

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
    #   - name: Commit and push changes
    #     run: |
    #       git config --local user.email "action@github.com"
    #       git config --local user.name "GitHub Action"
    #       git add README.md
    #       git commit -m "Generate README"
    #       git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
